# 기본 설정 (공통)
spring:
  profiles:
    active: dev  # 기본적으로 개발 환경 사용

# 공통 설정
openai:
  api-key: ${OPENAI_API_KEY:your-openai-api-key-here}
  model: gpt-4
  max-tokens: 2000
  temperature: 0.7

# 공통 로깅 설정
logging:
  level:
    com.macchain: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO

# 공통 관리 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
